USE [master]
GO

/****** Object:  Database [WerkgeverBeheer]    Script Date: 29-12-2014 09:07:46 ******/
CREATE DATABASE [WerkgeverBeheer]
 CONTAINMENT = NONE
GO

ALTER DATABASE [WerkgeverBeheer] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WerkgeverBeheer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WerkgeverBeheer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET ARITHABORT OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WerkgeverBeheer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WerkgeverBeheer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WerkgeverBeheer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WerkgeverBeheer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WerkgeverBeheer] SET  MULTI_USER 
GO

ALTER DATABASE [WerkgeverBeheer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WerkgeverBeheer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WerkgeverBeheer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WerkgeverBeheer] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WerkgeverBeheer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WerkgeverBeheer] SET  READ_WRITE 
GO

USE [WerkgeverBeheer]
GO

/****** Object:  Table [dbo].[Klant]    Script Date: 29-12-2014 09:08:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Werkgever](
	[Nummer] [nvarchar](50) NOT NULL,
	[Version] [int] NOT NULL,
	[BedrijfsNaam] [nvarchar](50) NOT NULL,
	[NaamContactpersoon] [nvarchar](50) NOT NULL,
	[EmailAdres] [nvarchar](125) NULL,
	[VestigingsAdresStraat] [nvarchar](125) NULL,
	[VestigingsAdresHuisnummer] [int] NULL,
	[VestigingsAdresHuisnummerToevoeging] [nvarchar](5) NULL,
	[VestigingsAdresPostcode] [nvarchar](10) NULL,
	[VestigingsAdresPlaats] [nvarchar](100) NULL,
	[Id] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Werkgever] PRIMARY KEY CLUSTERED 
(
	[Nummer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [master]
GO

/****** Object:  Login [WerkgeverBeheerUser]    Script Date: 29-12-2014 09:12:05 ******/
CREATE LOGIN [WerkgeverBeheerUser] WITH PASSWORD=0x0200E9C4DB32F27EBB492448BE076B9088122FA5810F439ED2C27BD0B238E631E36D970E33E75D39CC1CD793E5FC225C981F10B3CEBD25296D8BA3978EEFB6E413EC68377659 HASHED, 
DEFAULT_DATABASE=[WerkgeverBeheer], 
DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [WerkgeverBeheer]
GO

/****** Object:  User [WerkgeverBeheerUser]    Script Date: 29-12-2014 09:13:47 ******/
CREATE USER [WerkgeverBeheerUser] FOR LOGIN [WerkgeverBeheerUser] WITH DEFAULT_SCHEMA=[dbo]
GO

EXEC sp_addrolemember 'db_owner', 'WerkgeverBeheerUser';