USE [master]
GO

/****** Object:  Database [ProcesManagement]    Script Date: 29-12-2014 09:07:46 ******/
CREATE DATABASE [ProcesManagement]
 CONTAINMENT = NONE
GO

ALTER DATABASE [ProcesManagement] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProcesManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProcesManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProcesManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProcesManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProcesManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProcesManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProcesManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProcesManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProcesManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProcesManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProcesManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProcesManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProcesManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProcesManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProcesManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProcesManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProcesManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProcesManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProcesManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProcesManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProcesManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProcesManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProcesManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProcesManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProcesManagement] SET  MULTI_USER 
GO

ALTER DATABASE [ProcesManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProcesManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProcesManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProcesManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProcesManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProcesManagement] SET  READ_WRITE 
GO

USE [ProcesManagement]
GO

/****** Object:  Table [dbo].[Klant]    Script Date: 29-12-2014 09:08:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RegistrerenAanmelding](
	[CorrelationId] [uniqueidentifier] NOT NULL,
	[InitierendCommand] [text] NOT NULL,
	[DeelnemerNummer] [nvarchar](50) NULL,
	[WerkgeverNummer] [nvarchar](50) NULL,
	[StartTijdstip] [datetime2](7) NOT NULL,
	[Status] [nvarchar](15) NOT NULL,
	[Foutmelding] [text] NULL
 CONSTRAINT [PK_ProcesState] PRIMARY KEY CLUSTERED 
(
	[CorrelationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [master]
GO

/****** Object:  Login [ProcesManagementUser]    Script Date: 29-12-2014 09:12:05 ******/
CREATE LOGIN [ProcesManagementUser] WITH PASSWORD=0x0200E9C4DB32F27EBB492448BE076B9088122FA5810F439ED2C27BD0B238E631E36D970E33E75D39CC1CD793E5FC225C981F10B3CEBD25296D8BA3978EEFB6E413EC68377659 HASHED, 
DEFAULT_DATABASE=[ProcesManagement], 
DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [ProcesManagement]
GO

/****** Object:  User [ProcesManagementUser]    Script Date: 29-12-2014 09:13:47 ******/
CREATE USER [ProcesManagementUser] FOR LOGIN [ProcesManagementUser] WITH DEFAULT_SCHEMA=[dbo]
GO

EXEC sp_addrolemember 'db_owner', 'ProcesManagementUser';