USE [master]
GO

/****** Object:  Database [Correspondentie]    Script Date: 29-12-2014 09:07:46 ******/
CREATE DATABASE [Correspondentie]
 CONTAINMENT = NONE
GO

ALTER DATABASE [Correspondentie] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Correspondentie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Correspondentie] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Correspondentie] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Correspondentie] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Correspondentie] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Correspondentie] SET ARITHABORT OFF 
GO

ALTER DATABASE [Correspondentie] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Correspondentie] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Correspondentie] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Correspondentie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Correspondentie] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Correspondentie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Correspondentie] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Correspondentie] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Correspondentie] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Correspondentie] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Correspondentie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Correspondentie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Correspondentie] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Correspondentie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Correspondentie] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Correspondentie] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Correspondentie] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Correspondentie] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Correspondentie] SET  MULTI_USER 
GO

ALTER DATABASE [Correspondentie] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Correspondentie] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Correspondentie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Correspondentie] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Correspondentie] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Correspondentie] SET  READ_WRITE 
GO

USE [Correspondentie]
GO

/****** Object:  Table [dbo].[Klant]    Script Date: 29-12-2014 09:08:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Deelnemer](
	[Id] [uniqueidentifier] NOT NULL,
	[Nummer] [nvarchar](50) NOT NULL,
	[Naam] [nvarchar](50) NOT NULL,
	[EmailAdres] [nvarchar](125) NULL,
	[Straat] [nvarchar](125) NULL,
	[Huisnummer] [int] NULL,
	[HuisnummerToevoeging] [nvarchar](5) NULL,
	[Postcode] [nvarchar](10) NULL,
	[Plaats] [nvarchar](100) NULL,
 CONSTRAINT [PK_Deelnemer] PRIMARY KEY CLUSTERED 
(
	[Nummer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [master]
GO

/****** Object:  Login [CorrespondentieUser]    Script Date: 29-12-2014 09:12:05 ******/
CREATE LOGIN [CorrespondentieUser] WITH PASSWORD=0x0200E9C4DB32F27EBB492448BE076B9088122FA5810F439ED2C27BD0B238E631E36D970E33E75D39CC1CD793E5FC225C981F10B3CEBD25296D8BA3978EEFB6E413EC68377659 HASHED, 
DEFAULT_DATABASE=[Correspondentie], 
DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [Correspondentie]
GO

/****** Object:  User [CorrespondentieUser]    Script Date: 29-12-2014 09:13:47 ******/
CREATE USER [CorrespondentieUser] FOR LOGIN [CorrespondentieUser] WITH DEFAULT_SCHEMA=[dbo]
GO

EXEC sp_addrolemember 'db_owner', 'CorrespondentieUser';